name: Poll Data
env:
  START_TS: ""
  DISCORD_MSG: ""
on:
  workflow_dispatch:
  push:
    branches:
      - main
  # schedule:
  #   # every day at midnight
  #   - cron: "0 0 * * *"
jobs:
  poll-all:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v3
      - name: get start timestamp
        run: echo "START_TS=$(date +'%s')" >> "$GITHUB_ENV"
      - name: discord notification
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_NOTIFICATION_URL }}
          content: "⚙️  Poll run [#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) started (<t:${{ env.START_TS }}:R>)"
      - name: update apt
        run: sudo apt-get update
      - name: install poetry
        run: pipx install poetry
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "poetry"
      - name: display python version
        run: python -c "import sys; print(sys.version)"
      - name: install python dependencies
        run: poetry install --no-interaction --no-ansi
      - name: run scrapy
        run: poetry run python -m lib.scrapy.scripts.run_scrapy
      - name: set discord msg
        run: poetry run python -m lib.scrapy.scripts.set_discord_msg
      - name: archive logs
        uses: actions/upload-artifact@v4
        with:
          path: logs
      - name: commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🤖 automated poll update"
      - name: discord success notification
        if: ${{ success() }}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_NOTIFICATION_URL }}
          content: ${{ env.DISCORD_MSG }}
      - name: discord failure notification
        if: ${{ failure() }}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_NOTIFICATION_URL }}
          content: "😢  Poll run [#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) failed"
      - name: discord cancel notification
        if: ${{ cancelled() }}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_NOTIFICATION_URL }}
          content: "❌  Poll run [#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) cancelled"
